manipulator:
  joint1:
    joint_controller:
      type: "effort_controllers/JointPositionController"
      joint: "motor1"
  joint2:
    joint_controller:
      type: "effort_controllers/JointPositionController"
      joint: "motor2"
  joint3:
    joint_controller:
      type: "effort_controllers/JointPositionController"
      joint: "motor3"
  joint4:
    joint_controller:
      type: "effort_controllers/JointPositionController"
      joint: "motor4"
  joint5:
    joint_controller:
      type: "effort_controllers/JointPositionController"
      joint: "motor5"
  joint6:
    joint_controller:
      type: "effort_controllers/JointPositionController"
      joint: "motor6"
